spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            identityprovider:
              metadata-uri: https://dev-805262.oktapreview.com/app/exkqetoqvtEtScSKT0h7/sso/saml/metadata


logging.level:
  org.springframework.security: TRACE
